name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.3
            cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
            terraform_wrapper: false
    
        - name: Terraform Init
          run: terraform init

        - name: Extract Terraform output
          id: tf-output
          run: |
            PUBLIC_IP=$(terraform output -raw public_ip)
            echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
        
        - name: Install Docker on VM
          env:
              PUBLIC_IP: ${{ steps.tf-output.outputs.public_ip }}
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
              echo "$SSH_PRIVATE_KEY" > private_key.pem
              chmod 600 private_key.pem
              ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$PUBLIC_IP << 'EOF'
              sudo apt-get update
              sudo apt-get install ca-certificates curl
              sudo install -m 0755 -d /etc/apt/keyrings
              sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
              sudo chmod a+r /etc/apt/keyrings/docker.asc
              echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
              # Add more commands as needed
              EOF